FROM registry.access.redhat.com/ubi9/python-311

WORKDIR /opt/app-root/src

USER 1001

COPY --chown=1001:0 requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt && \
    rm -f requirements.txt && \
    # Fix permissions to support pip in Openshift environments \
    chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    fix-permissions /opt/app-root -P

COPY --chown=1001:0 app-react.py standard_scaler.pkl target_scaler.pkl tool_list_operators.py tool_mlasp.py \
                    tool_prometheus.py tool_rag.py tool_summarize_states.py tools_input_schema.py ./
COPY --chown=1001:0 assets/ ./assets/

EXPOSE  7860

CMD ["python", "app-react.py"]